name: OpenMP MacOS build
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: build on macos
        run: |
          brew install libomp llvm
          /usr/local/opt/llvm/bin/clang -fopenmp -L/usr/local/opt/llvm/lib omp_hello.c -o hello
          #clang -fopenmp omp_hello.c -o hello
          ./hello
          ldd hello
