name: OpenMP MacOS build
on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.5]
    steps:
      - uses: actions/checkout@v1
      - name: build on macos
        run: |
          brew install libomp
          clang omp_hello.c -o hello
          ./hello
